#!/usr/bin/env python3
"""Render hash-checked ARM64 runtime/test locks from an audited pip resolver report.

Run on Python 3.12 with --report PATH. The report must resolve the three exact
nightly wheels in nightly-pins.json and all runtime dependencies. It may resolve
them from local wheel files; the output uses verified canonical HTTPS URLs.
The test-only packages are separated from the runtime image.
"""

import argparse
import json
from pathlib import Path
import re
from urllib.parse import urlsplit

HERE = Path(__file__).resolve().parent
TEST_ONLY = {"pytest", "pluggy", "iniconfig"}
ALLOWED_HOSTS = {"download.pytorch.org", "files.pythonhosted.org"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    if args.report.stat().st_size > 2 * 1024**2:
        raise ValueError("pip report exceeds the 2 MiB audit limit")
    report = json.loads(args.report.read_text())
    pins = json.loads((HERE / "nightly-pins.json").read_text())
    environment = report["environment"]
    if environment["platform_machine"] != "aarch64" or environment["python_version"] != pins["python"]:
        raise ValueError("resolve the dependency report on ARM64 Python 3.12")
    entries = report["install"]
    if not isinstance(entries, list) or not 1 <= len(entries) <= 256:
        raise ValueError("invalid dependency count")
    seen, runtime, test = set(), [], []
    for item in entries:
        name = re.sub(r"[-_.]+", "-", item["metadata"]["name"]).lower()
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name) or name in seen:
            raise ValueError("invalid or duplicate dependency name")
        seen.add(name)
        version = item["metadata"]["version"]
        download = item["download_info"]
        digest = download["archive_info"]["hashes"]["sha256"]
        url = download["url"]
        if name in pins["wheels"]:
            pin = pins["wheels"][name]
            if version != pin["version"] or digest != pin["sha256"]:
                raise ValueError(f"resolver changed the audited {name} wheel")
            url = pin["url"]
        parsed = urlsplit(url)
        if parsed.scheme != "https" or parsed.hostname not in ALLOWED_HOSTS or parsed.username or parsed.password:
            raise ValueError(f"unapproved dependency origin for {name}")
        if any(character.isspace() for character in url) or not parsed.path.endswith(".whl"):
            raise ValueError(f"dependency must be a wheel URL: {name}")
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise ValueError(f"invalid SHA256 for {name}")
        line = f"{name} @ {url} --hash=sha256:{digest}\n"
        (test if name in TEST_ONLY else runtime).append((name, line))
    if not set(pins["wheels"]) <= seen or not TEST_ONLY <= seen:
        raise ValueError("report omitted required nightly or verification packages")
    banner = "# Generated by lock_dependencies.py from the ARM64 pip report; update pins and regenerate.\n"
    for filename, rows in [("requirements-runtime.lock", runtime), ("requirements-test.lock", test)]:
        content = banner + "".join(line for _, line in sorted(rows))
        (HERE / filename).write_text(content)
    print(f"Locked {len(runtime)} runtime and {len(test)} test packages")


if __name__ == "__main__":
    main()
